#!/usr/bin/env Rscript

# Reproducible before/after proof for issue #232.
output_dir <- file.path(".github", "landing-proof", "issue-232")
scratch_dir <- file.path(".scratch", "issue-232-contact-sheet")
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(scratch_dir, recursive = TRUE, showWarnings = FALSE)
file.copy(
    file.path(".github", "landing-proof", "issue-226", "adversarial-review.md"),
    file.path(scratch_dir, "adversarial-review.md"), overwrite = TRUE
)
Sys.setenv(LANDSCAPER_CONTACT_SHEET_OUTPUT = scratch_dir)
source(file.path("scripts", "render-issue-226-contact-sheet.R"), local = new.env())

required <- c(
    "public-plot-contact-sheet.png",
    "public-plot-contact-sheet-reduced.png",
    "public-plot-contact-sheet-caption.txt",
    "public-plot-contact-sheet-labels.tsv"
)
stopifnot(all(file.exists(file.path(scratch_dir, required))))
stopifnot(file.exists(file.path(output_dir, "contact-sheet-before.png")))
stage_artifacts <- c(
    "stage1-components-categorical.png",
    "stage1-components-categorical-caption.txt",
    "stage1-components-continuous.png",
    "stage1-components-continuous-caption.txt",
    "stage1-decomposition.png",
    "stage1-decomposition-caption.txt",
    "stage1-spectrum.png",
    "stage1-spectrum-caption.txt",
    "stage2-potential.png",
    "stage2-potential-caption.txt",
    "stage2-potential-critical-points.png",
    "stage2-potential-critical-points-caption.txt"
)
stopifnot(all(file.exists(file.path(scratch_dir, stage_artifacts))))
stage_proof_dir <- file.path(".github", "landing-proof", "issue-226")
file.copy(
    file.path(scratch_dir, stage_artifacts),
    file.path(stage_proof_dir, stage_artifacts),
    overwrite = TRUE
)
file.copy(
    file.path(scratch_dir, "public-plot-contact-sheet.png"),
    file.path(output_dir, "contact-sheet-after.png"), overwrite = TRUE
)
file.copy(
    file.path(scratch_dir, "public-plot-contact-sheet-reduced.png"),
    file.path(output_dir, "contact-sheet-after-reduced.png"), overwrite = TRUE
)
file.copy(
    file.path(scratch_dir, "public-plot-contact-sheet-caption.txt"),
    file.path(output_dir, "contact-sheet-after-caption.txt"), overwrite = TRUE
)
file.copy(
    file.path(scratch_dir, "public-plot-contact-sheet-labels.tsv"),
    file.path(output_dir, "contact-sheet-after-labels.tsv"), overwrite = TRUE
)
writeLines(c(
    "# Issue #232 contact-sheet tile-isolation proof", "",
    "The before image is the issue #226 contact sheet whose full plot subtitles",
    "collided across tile boundaries at reduced reading size.", "",
    "The after image uses concise tile-local labels and suppresses only the",
    "underlying plot subtitles in the audit sheet. Full scientific captions remain",
    "in the issue #226 inventory and separate caption files.", "",
    "The retained Stage 1 and Stage 2 figures and captions are regenerated from",
    "the same renderer, including the declared low reference and high focal",
    "palette used by the public plot functions. Other issue #226 families are",
    "intentionally not regenerated by this proof.", "",
    "The reduced after image is the required smaller-dimension QA render. The",
    "label manifest records the bounded text budget checked by the renderer and",
    "contract checker. Inspect both after images for tile isolation, label",
    "legibility, clipping, and legend collisions.", "",
    "Reproduce with:", "", "Rscript scripts/render-issue-232-proof.R", "",
    "Claim status: implementation proof; no biological claim."
), file.path(output_dir, "README.md"))
